---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

environment:
  DOCKER_BUILDKIT: "1"

volumes:
  - name: static
    host:
      path: /static/meilisearch

steps:
  - name: build
    image: node:16-alpine
    volumes:
      - name: static
        path: /app/build
    commands:
      - npm install
      - npm run build
      - mv build/* /app/build/

  - name: docker
    image: plugins/docker
    settings:
      auto_tag: true
      build_args:
        - BUILDKIT_INLINE_CACHE=1
      password:
        from_secret: docker_password
      repo: alinpanaitiu/meilidash
      username: alinpanaitiu
      purge: false
      cache_from:
        - alinpanaitiu/meilidash:latest

  - name: deploy
    image: curlimages/curl
    commands:
      - curl -L -s -S https://alin:$${DEPLOY_PASSWORD}@deploy.darkwoods.win/meili
    environment:
      DEPLOY_PASSWORD:
        from_secret: deploy_password
    when:
      branch:
        - main
        - master
    depends_on:
      - build
      - docker

---
kind: signature
hmac: 7db2380168ee241a17a35a012e1ce842139fd9f962e29c054c03dcdf12336f09

...
