version: "3.8"

x-refs:
  restart: &restart
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      rollback_config:
        parallelism: 2
      update_config:
        parallelism: 2
  server: &server
    image: getmeili/meilisearch:v0.25.0
    command: sh -c 'rm -rf /database/data.ms; /bin/meilisearch --ignore-missing-snapshot --ignore-snapshot-if-db-exists --import-snapshot /snapshots/data.ms.snapshot'
    user: root
    container_name: meilisearch
    <<: *restart
    networks:
      - meili
    ports:
      - 7700:7700
    environment:
      MEILI_ENV: production
      MEILI_MASTER_KEY:
      MEILI_NO_SENTRY: "true"
      MEILI_DUMPS_DIR: /dumps
      MEILI_DB_PATH: /database/data.ms
      MEILI_SNAPSHOT_DIR: /snapshots
      MEILI_SCHEDULE_SNAPSHOT: "true"
      MEILI_SNAPSHOT_INTERVAL_SEC: "1800"

networks:
  meili:

volumes:
  data0:
  data1:
  data2:
  dumps0:
  dumps1:
  dumps2:
  snapshots0:
  snapshots1:
  snapshots2:

services:
  server0:
    <<: *server
    ports:
      - 7700:7700
    volumes:
      - data0:/database
      - dumps0:/dumps
      - snapshots0:/snapshots

  server1:
    <<: *server
    ports:
      - 7701:7700
    volumes:
      - data1:/database
      - dumps1:/dumps
      - snapshots1:/snapshots

  server2:
    <<: *server
    ports:
      - 7702:7700
    volumes:
      - data2:/database
      - dumps2:/dumps
      - snapshots2:/snapshots
  # dashboard:
  #   build:
  #     context: .
  #     args:
  #       - BUILDKIT_INLINE_CACHE=1
  #     cache_from:
  #       - alinpanaitiu/meilidash:latest
  #   image: alinpanaitiu/meilidash:latest
  #   container_name: meilidash
  #   <<: *restart
  #   networks:
  #     - meili
  #   ports:
  #     - 5002:5000
  #   environment:
  #     NODE_ENV: production
