version: "3.8"

x-refs:
  restart: &restart
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      rollback_config:
        parallelism: 2
      update_config:
        parallelism: 2
  server: &server
    image: getmeili/meilisearch:v0.24.0
    command: ./meilisearch --import-dump /dumps/latest.dump --db-path /data.ms
    user: root
    container_name: meilisearch
    <<: *restart
    networks:
      - meili
    ports:
      - 7700:7700
    environment:
      MEILI_ENV: production
      MEILI_MASTER_KEY:
      MEILI_NO_SENTRY: "true"

networks:
  meili:

volumes:
  data0:
  data1:
  data2:
  dumps0:
  dumps1:
  dumps2:
  snapshots0:
  snapshots1:
  snapshots2:

services:
  server0:
    <<: *server
    ports:
      - 7700:7700
    volumes:
      - data0:/data.ms
      - dumps0:/dumps
      - snapshots0:/snapshots

  server1:
    <<: *server
    ports:
      - 7701:7700
    volumes:
      - data1:/data.ms
      - dumps1:/dumps
      - snapshots1:/snapshots

  server2:
    <<: *server
    ports:
      - 7702:7700
    volumes:
      - data2:/data.ms
      - dumps2:/dumps
      - snapshots2:/snapshots
  # dashboard:
  #   build:
  #     context: .
  #     args:
  #       - BUILDKIT_INLINE_CACHE=1
  #     cache_from:
  #       - alinpanaitiu/meilidash:latest
  #   image: alinpanaitiu/meilidash:latest
  #   container_name: meilidash
  #   <<: *restart
  #   networks:
  #     - meili
  #   ports:
  #     - 5002:5000
  #   environment:
  #     NODE_ENV: production
